[package]
name = "xarm_servo_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
hidapi = "2.6.3"
strum = "0.26.3"
strum_macros = "0.26.4"

[[bin]]
name = "robot_controller"
path = "src/main.rs"

[lib]
name = "robot_controller"
path = "src/lib.rs"
